google_provider_version      = "6.13.1"
google_beta_provider_version = "6.13.1"
environment_name             = "prod"
project_id                   = "surf-city-softball-prod"
project_name                 = "surf-city-softball-prod"
region                       = "us-west2"
bucket                       = "surf-city-softball-prod"
