# name: CD (Dev)

# on:
#   push:
#     branches:
#       - master
#   workflow_run:
#     workflows: ["CI"]  # Name of your CI workflow (ci.yml)
#     types:
#       - completed  # Runs when CI finishes

# jobs:
#   CD:
#     name: CD (Dev)
#     runs-on: macos-15

#     # checkout source code
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       # install terraform
#       - name: Setup Terraform
#         uses: hashicorp/setup-terraform@v3
#         with:
#           terraform_version: 1.10.3

#       # deploy terraform 
#       - name: Show Terraform version
#         run: |
#           set -e
#           INFRA_DIR="infrastructure"

#           for dir in $(find "$INFRA_DIR" -type f -name "*.tf" -exec dirname {} \; | sort -u); do
#               echo "🚀 Processing Terraform in $dir"
#               cd "$dir"

#               echo "🔹 Initializing Terraform..."
#               terraform init -backend-config="envs/dev.backend"

#               echo "🔹 Validating Terraform configuration..."
#               terraform validate -var-file="envs/dev.tfvars"

#               echo "🔹 Planning Terraform changes..."
#               terraform plan -out=tfplan -var-file="envs/dev.tfvars"

#               echo "🔹 Applying Terraform changes..."
#               terraform apply -var-file="envs/dev.tfvars" -auto-approve tfplan
#           done
