# CI workflow that runs when a pull request is merged into the master branch
name: CD (Dev)

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - master

jobs:
  CD:
    permissions:
      id-token: write
      contents: read

    name: CD (Dev)
    runs-on: macos-15

    steps:
      # checkout source code
      - name: Checkout repository
        uses: actions/checkout@v4

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          create_credentials_file: true
          workload_identity_provider: "projects/286242985148/locations/global/workloadIdentityPools/surf-city-softball-wif-pool-dev/providers/surf-city-softball-wif-prov-dev"
          service_account: "terraform-sa-dev@surf-city-softball-dev.iam.gserviceaccount.com"

      # install terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.3
      # deploy terraform
      - name: Deploy Terraform
        run: |
          set -e
          INFRA_DIR="infrastructure"
          for dir in $(find "$INFRA_DIR" -type f -name "*.tf" -exec dirname {} \; | sort -u); do
              echo "🚀 Processing Terraform in $dir"
              cd "$dir"
              echo "🔹 Initializing Terraform..."
              terraform init -backend-config="envs/dev.backend"
              echo "🔹 Validating Terraform configuration..."
              terraform validate
              echo "🔹 Planning Terraform changes..."
              terraform plan -out=tfplan -var-file="envs/dev.tfvars"
              echo "🔹 Applying Terraform changes..."
              terraform apply -var-file="envs/dev.tfvars" -auto-approve tfplan
          done
