name: CI
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  CI:
    name: CI
    runs-on: macos-15

    # checkout source code
    steps:
    - uses: actions/checkout@v4
      name: Checkout source code

    # install TFLint plugins
    - uses: actions/cache@v4
      name: Cache plugin dir
      with:
        path: ~/.tflint.d/plugins
        key: macos-15-tflint-${{ hashFiles('.tflint.hcl') }}

    # setup TFLint
    - uses: terraform-linters/setup-tflint@v4
      name: Setup TFLint
      with:
        tflint_version: v0.52.0

    # show TFLint version
    - name: Show version
      run: tflint --version

    # init TFLint
    - name: Init TFLint
      run: tflint --init

    # run TFLint
    - name: Run TFLint
      run: tflint -f compact

  CD:
    name: CD (Dev)
    runs-on: macos-15

    # checkout source code
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # install terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.3

      # deploy terraform 
      - name: Show Terraform version
        run: |
          set -e
          INFRA_DIR="infrastructure"

          for dir in $(find "$INFRA_DIR" -type f -name "*.tf" -exec dirname {} \; | sort -u); do
              echo "🚀 Processing Terraform in $dir"
              cd "$dir"

              echo "🔹 Initializing Terraform..."
              terraform init -backend-config="envs/dev.backend"

              echo "🔹 Validating Terraform configuration..."
              terraform validate -var-file="envs/dev.tfvars"

              echo "🔹 Planning Terraform changes..."
              terraform plan -out=tfplan -var-file="envs/dev.tfvars"

              echo "🔹 Applying Terraform changes..."
              terraform apply -var-file="envs/dev.tfvars" -auto-approve tfplan
          done
