on: push

jobs:
  CI:
    runs-on: macos-15 
    name: CI

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Terrascan
      id: terrascan
      uses: tenable/terrascan-action@main
      with:
        iac_type: 'terraform'
        iac_version: 'v1'
        policy_type: 'gcp'
        iac_dir: './infrastruture'