name: CI

on: push

jobs:
  CI:
    name: CI
    runs-on: macos-15
    steps:

      # checkout code
      - name: Checkout code
        uses: actions/checkout@v4
      
      # setup terraform linter 
      - uses: terraform-linters/setup-tflint@v4
        name: Setup TFLint
        with:
          tflint_version: v0.52.0

      # initialize TFLint
      - name: Init TFLint
        run: tflint --init
        env:
          GITHUB_TOKEN: ${{ github.token }}

      # Run TFLint
      - name: Run TFLint
        run: tflint -f compact

